# If you do not have OpenSSL installed, change
# the following line to use "http://"
source "https://rubygems.org"

gem "attr_extras"
gem "bourbon", "~> 4.2"
gem "builder", "~> 3.0"
gem "middleman", "~> 4.0"
gem "middleman-autoprefixer", "~> 2.6"
gem "middleman-blog"
gem "middleman-deploy", "= 2.0.0.pre.alpha"
gem "middleman-livereload", "~> 3.4"
gem "middleman-pry"
gem "middleman-sprockets", "= 4.0.0.rc.1"
gem "middleman-syntax"
gem "neat", "~> 1.7"
gem "sassc", "~> 1.8"
