# If you do not have OpenSSL installed, change
# the following line to use "http://"
source "https://rubygems.org"

gem "attr_extras"
gem "bourbon", "~> 5.0"
gem "builder", "~> 3.0"
gem "font-awesome-middleman"
gem "middleman", "~> 4.5"
gem "middleman-autoprefixer", "~> 3.0"
gem "middleman-blog"
gem "middleman-deploy", "= 2.0.0.pre.alpha"
gem "middleman-livereload"
gem "middleman-sprockets", "~> 4.1"
gem "middleman-syntax"
gem "neat", "~> 1.9"
gem "net-ftp"
gem "sassc", "~> 2.4"
